"""Embed Pixel Operator into the mockup harness as a data URI.

    python scripts/make-mock-font.py

Writes docs/ui/mock/pixel-operator.css, which harness.css imports.

A mockup has to open from the filesystem with a double-click — that is most of what makes
the browser half of the design loop cheap. Chrome refuses to load a `file://` font through
`url()` (it is a cross-origin request from a file page), so a relative path to
assets/fonts/PixelOperator.ttf works in one browser and silently falls back to a system face
in another. A silent fallback is the worst outcome available: the mockup still looks fine,
and every measurement taken off it is wrong.

The face is 17KB, so embedding it costs ~23KB of base64 and removes the question.

CC0 1.0 (public domain) — see assets/fonts/PixelOperator-LICENSE.txt.
"""

import base64
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
TTF = REPO / "assets" / "fonts" / "PixelOperator.ttf"
OUT = REPO / "docs" / "ui" / "mock" / "pixel-operator.css"

HEADER = """\
/* Generated by scripts/make-mock-font.py — do not edit by hand.
 *
 * Pixel Operator, the game's UI face (presentation/ui.odin bakes the same file), embedded as
 * a data URI so a mockup opens from the filesystem in any browser rather than silently
 * falling back to a system face and quietly invalidating every measurement taken off it.
 *
 * CC0 1.0 (public domain) — assets/fonts/PixelOperator-LICENSE.txt.
 */
@font-face {
  font-family: "Pixel Operator";
  font-style: normal;
  font-weight: 400;
  src: url("data:font/ttf;base64,%s") format("truetype");
}
"""


def main():
    encoded = base64.b64encode(TTF.read_bytes()).decode("ascii")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(HEADER % encoded, newline="\n")
    print(f"wrote {OUT.relative_to(REPO)} ({len(encoded)} base64 chars)")


if __name__ == "__main__":
    main()
