"""Render a screen's mockups, assemble them side by side, and measure how far apart they are.

    python scripts/mock-divergence.py shop

Renders every `docs/ui/mock/<screen>/*.html` headlessly at 1244x700, writes `index.html`
holding them side by side at full resolution, and prints the **pairwise identical-pixel
percentage**.

That last number is the point. A four-way design exploration on this repo once produced
variants that were 82% pixel-identical, and nobody noticed until they were measured — four
options that look like four options and are one. So `design-a-screen` measures its own output
rather than asserting it diverged: a run whose pairs sit near 82% has not diverged, and the
briefs are what to fix, not the agents.

Rendering needs a Chromium — Edge or Chrome, whichever is installed. Without one the page is
still assembled and only the measurement is skipped, because the page is what a human judges
by and the number is the skill's own test.
"""

import itertools
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
MOCK = REPO / "docs" / "ui" / "mock"

STAGE_W, STAGE_H = 1244, 700

CHROMIUM = (
    Path(r"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe"),
    Path(r"C:\Program Files\Microsoft\Edge\Application\msedge.exe"),
    Path(r"C:\Program Files\Google\Chrome\Application\chrome.exe"),
    Path("/usr/bin/chromium"),
    Path("/usr/bin/google-chrome"),
)

# Two mockups this alike are the same mockup wearing a different number.
SUSPICIOUS_OVERLAP = 70.0


def browser():
    for candidate in CHROMIUM:
        if candidate.is_file():
            return candidate
    return None


def render(exe, page, out):
    """One mockup's stage as a PNG. The window is the stage plus the margin harness.css
    leaves, so the shot contains the whole 1244x700 and nothing of the caption."""
    subprocess.run(
        [
            str(exe),
            "--headless=new",
            "--disable-gpu",
            "--hide-scrollbars",
            f"--window-size={STAGE_W + 6},{STAGE_H + 48}",
            f"--screenshot={out}",
            page.resolve().as_uri(),
        ],
        capture_output=True,
        check=False,
    )
    return out.is_file()


def identical_fraction(a, b):
    """The share of pixels two shots agree on, as a percentage."""
    from PIL import Image, ImageChops

    left, right = Image.open(a).convert("RGB"), Image.open(b).convert("RGB")
    if left.size != right.size:
        return None
    delta = ImageChops.difference(left, right)
    red, green, blue = delta.split()
    changed = sum(ImageChops.lighter(ImageChops.lighter(red, green), blue).histogram()[1:])
    total = left.width * left.height
    return 100 * (total - changed) / total


INDEX = """\
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>%(screen)s — %(count)d options</title>
    <style>
      body {
        margin: 0;
        padding: 24px;
        background: #181818;
        color: #c8c8c8;
        font: 14px/1.5 system-ui, sans-serif;
      }
      h1 { color: #fff; font-size: 20px; margin: 0 0 4px; }
      p.lede { margin: 0 0 24px; max-width: 900px; }
      .row { display: flex; gap: 24px; overflow-x: auto; padding-bottom: 24px; }
      .option { flex: 0 0 auto; }
      .option h2 { color: #fff; font-size: 16px; margin: 0 0 8px; }
      .option iframe { width: %(w)dpx; height: %(h)dpx; border: 1px solid #333; display: block; }
      code { color: #ffd479; }
      table { border-collapse: collapse; margin: 0 0 24px; }
      td { padding: 2px 16px 2px 0; }
      td.n { text-align: right; color: #fff; }
      td.hot { color: #ff8f6b; }
    </style>
  </head>
  <body>
    <h1>%(screen)s — %(count)d options, side by side at full resolution</h1>
    <p class="lede">
      Generated by the <code>design-a-screen</code> skill: %(count)d sub-agents in parallel, no
      shared context, one governing constraint each. Scroll sideways. Each option's own note is
      under it, inside its frame.
    </p>
    <p class="lede">
      <strong>Rejected directions are kept, not deleted.</strong> The cost of keeping one forever
      is a file, and a direction that was not chosen is still a data point about what this game
      looks like. Record the pick and the reasons below rather than removing anything.
    </p>
    <p class="lede"><strong>Chosen:</strong> <em>not yet decided</em></p>
%(divergence)s
    <div class="row">
%(options)s
    </div>
  </body>
</html>
"""

DIVERGENCE = """\
    <p class="lede">
      <strong>Measured divergence</strong> — the share of pixels each pair agrees on. The failure
      this skill exists to fix sat at <strong>82%%</strong>, so these are the numbers that say
      whether the briefs worked. Closest pair here: <strong>%(worst).1f%%</strong>.
    </p>
    <table>
%(rows)s
    </table>
"""

OPTION = """\
      <div class="option">
        <h2>%(title)s</h2>
        <iframe src="%(file)s" title="%(title)s"></iframe>
      </div>
"""


def main():
    if len(sys.argv) != 2:
        sys.exit("usage: python scripts/mock-divergence.py <screen>")
    screen = sys.argv[1]
    folder = MOCK / screen
    if not folder.is_dir():
        sys.exit(f"no mockups at {folder}")

    pages = sorted(p for p in folder.glob("*.html") if p.name != "index.html")
    if not pages:
        sys.exit(f"no mockups in {folder}")

    pairs, worst = measure(folder, pages)

    divergence = ""
    if pairs:
        rows = "".join(
            f'      <tr><td>{a} vs {b}</td>'
            f'<td class="n{" hot" if same >= SUSPICIOUS_OVERLAP else ""}">{same:.1f}%</td></tr>\n'
            for a, b, same in pairs
        )
        divergence = DIVERGENCE % {"worst": worst, "rows": rows}

    index = folder / "index.html"
    index.write_text(
        INDEX
        % {
            "screen": screen,
            "count": len(pages),
            "w": STAGE_W,
            "h": STAGE_H,
            "divergence": divergence,
            "options": "".join(
                OPTION % {"title": p.stem.replace("-", " "), "file": p.name} for p in pages
            ),
        },
        newline="\n",
    )
    print(f"wrote {index.relative_to(REPO)} — {len(pages)} options")

    if worst >= SUSPICIOUS_OVERLAP:
        sys.exit(
            f"at least one pair is {worst:.1f}% identical, which is where the failure this "
            f"skill exists to fix sat (82%). Rewrite the briefs, not the mockups."
        )


def measure(folder, pages):
    """Every pair's identical-pixel share, and the worst of them. Empty when there is no
    browser to render with — the page is still worth assembling, since a human judges by it
    and the number is only the skill's own test."""
    exe = browser()
    if exe is None:
        print("no Chromium found; skipping the divergence measurement")
        return [], 0.0

    shots = {}
    out_dir = folder / "render"
    out_dir.mkdir(exist_ok=True)
    for page in pages:
        shot = out_dir / f"{page.stem}.png"
        if render(exe, page, shot):
            shots[page.stem] = shot
        else:
            print(f"  could not render {page.name}")

    if len(shots) < 2:
        print("fewer than two rendered; nothing to compare")
        return [], 0.0

    print("\npairwise identical pixels:")
    pairs, worst = [], 0.0
    for a, b in itertools.combinations(sorted(shots), 2):
        same = identical_fraction(shots[a], shots[b])
        if same is None:
            print(f"  {a} vs {b}: different sizes")
            continue
        flag = "  <-- these are the same mockup" if same >= SUSPICIOUS_OVERLAP else ""
        print(f"  {a} vs {b}: {same:.1f}%{flag}")
        pairs.append((a, b, same))
        worst = max(worst, same)

    print(f"\nclosest pair: {worst:.1f}% identical")
    return pairs, worst


if __name__ == "__main__":
    main()
